[package]
name = "postgres-lib"
version = "0.1.0"
authors = ["luke.simpson <luke.simpson@ruralsourcing.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.15.2"
